### ISSUE TITLE
[bug] Features: exception is thrown while enabling a feature

### ISSUE THREAD

**Issue by remon-nashid** [PolymathNetwork/polymath-sdk#101] opened 2019-10-23 17:32 UTC
Code sample https://github.com/PolymathNetwork/permissions/blob/master/src/App.js#L237
Test app: https://polymathnetwork.github.io/permissions/

**Comment by monitz87** [comment] 2019-10-25 03:28
This error is caused by a bug in the contract-wrappers package which is being addressed by an open PR

**Closed** 2019-10-31 14:16 UTC
Labels: bug, high-priority
